server:
  port: 8888
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/devgroundtc.p12
    key-store-password: password
    key-alias: devgroundtc
    enabled: true
    trust-store: classpath:keystore/cacerts
    trust-store-password: changeit

users:
  api:
    url: https://dg-users:8889/api/v1/users

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/dg-user-api
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true

jwt:
  secret: vlkdfjekDSDfndfsDFnlsfjslkjsflksIHKJHKJFBdGJYFHJdsfvvd
  token:
    validity: 86400000